### ISSUE TITLE
`IntrospectTypeRef` instance for `UUID`

### ISSUE THREAD

**Issue by rynoV** [higherkindness/mu-haskell#342]
When I use a schema with a field of type `ID`, and generate the service definition with `Mu.GraphQL.Quasi.graphql`, it uses `UUID` as the type of the field, but I end up with the error:

```
No instance for (mu-graphql-0.4.1.0:Mu.GraphQL.Query.Introspection.IntrospectTypeRef
                         ('Mu.Rpc.PrimitiveRef
                            uuid-types-1.0.3:Data.UUID.Types.Internal.UUID))
```

It seems like this instance could be added and maybe it was just forgotten about.

**Comment by serras** [comment]
Currently uploading version 0.5.0.4 which should fix this problem. Thanks for reporting!

**Comment by rynoV** [comment]
Thanks!

**Comment by rynoV** [comment]
@serras It seems like somewhere along the way between `mu-graphql-0.4.1.0` (the version I was using when I opened this issue) and `0.5.0.3`, the `ID` scalar stopped being interpreted by the quasi quoter as a `UUID`. So the generated code for an `ID` field now looks like

```haskell
'Mu.Rpc.Method "id" '[] ('Mu.Rpc.RetSingle ('Mu.Rpc.ObjectRef "ID")),
```

instead of before where it was something like:

```haskell
'Mu.Rpc.Method "id" '[] ('Mu.Rpc.RetSingle ('Mu.Rpc.PrimitiveRef UUID)),
```

so adding the instance did not fix the issue.

**Comment by serras** [comment]
According to the [official docs](https://graphql.org/learn/schema/#scalar-types), the `ID` scalar just represents a unique identifier, but doesn't state it should be a UUID. This is why we ultimately went with the [semi-official `UUID`](https://the-guild.dev/graphql/scalars/docs/scalars/uuid). But I'm happy to hear other options (maybe configure the parsing somehow?)

**Comment by rynoV** [comment]
Ah okay, I was trying to use `ID` instead of `UUID`, but adding `scalar UUID` and using `UUID` instead seems to work. Thanks!
